# Site settings
title: Amber Caldwell
timezone: America/New_York
baseurl: "http://ambercaldwell.net" # the subpath of your site, e.g. /blog/
url: "http://acaldwell710.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Scripts
# #1
google_analytics: "UA-98103851-1"
